preciosa/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include
from rest_framework import routers
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.views import APIView
from preciosa.api import views


class MyRouter(routers.DefaultRouter):

    def get_api_root_view(self):
        """
        Es la misma implementacion de la api root view de del
        DefaultRouter, pero con urls nuestras registradas.

        No es muy elegante, pero no encontré otra forma de
        registrar urls propias y las automaticas generadas por el router
        """
        api_root_dict = {}
        list_name = self.routes[0].name
        for prefix, viewset, basename in self.registry:
            api_root_dict[prefix] = list_name.format(basename=basename)

        class APIRoot(APIView):
            _ignore_model_permissions = True

            def get(self, request, format=None):
                ret = {
                    'sucursales': reverse('sucursales', request=request),
                    'productos': reverse('productos', request=request),
                    'precios': reverse('precios', request=request),
                    'donde_queda': reverse('donde_queda', request=request),
                    # listar acá otras urls que queremos que aparezcan en
                    # la home de la API
                }
                for key, url_name in api_root_dict.items():
                    ret[key] = reverse(url_name, request=request, format=format)
                return Response(ret)

        return APIRoot.as_view()


router = MyRouter()
router.register(r'cadenas', views.CadenaViewSet)
router.register(r'ciudades', views.CityViewSet)
router.register(r'marcas', views.MarcaViewSet)
router.register(r'fabricantes', views.EmpresaFabricanteViewSet)
router.register(r'categorias', views.CategoriaViewSet)


urlpatterns = patterns("preciosa.api.views",
    url(r"^sucursales/$", views.SucursalesList.as_view(), name='sucursales'),
    url(r"^sucursales/(?P<pk>\d+)$", views.SucursalesList.as_view(),
        name='sucursal_detalle'),
    url(r"^sucursales/(?P<pk>\d+)/productos$",
        views.ProductosList.as_view(),
        name='productos_con_precio_en_sucursal'),
    url(r"^sucursales/(?P<pk_sucursal>\d+)/productos/(?P<pk_producto>\d+)$",
        views.producto_sucursal_detalle,
        name='producto_detalle'),
    url(r"^productos/$", views.ProductosList.as_view(), name='productos'),

    url(r"^productos/(?P<pk>\d+)$", views.ProductosList.as_view(), name='productos'),
    url(r"^precios/$", views.PreciosList.as_view(), name='precios'),
    url(r"^utils/donde_queda$", views.donde_queda, name='donde_queda'),

    url(r"^", include(router.urls))

)

urlpatterns += patterns('',
    url(r'^auth/token$', 'rest_framework.authtoken.views.obtain_auth_token'),
    url(r'^auth/registro$', views.registro, name='registro')
)

preciosa/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from precios import views

from accounts.views import SignupView

from django.views.generic.base import RedirectView

import autocomplete_light
autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns("",
    url(r'^api/v1/', include("preciosa.api.urls")),  # noqa
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/signup/$", SignupView.as_view(
        template_name_email_confirmation_sent='account/email/template_name_email_confirmation_sent')),
    url(r"^account/", include("account.urls")),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'^imperavi/', include('imperavi.urls')),
    url(r'^buscador/', views.buscador, name='buscador'),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^(\d+)-([a-z0-9-_]+)/$',
        views.ProductosListView.as_view(), name='lista_productos'),
    url(r'^(\d+)-([a-z0-9-_]+)/(?P<pk>\d+)-([a-z0-9-_]+)$',
        views.ProductoDetailView.as_view(),
        name='detalle_producto'),
    url(r'^home/$', RedirectView.as_view(url='/'), name='home'),


    url(r'^blog/', include('radpress.urls')),
    url(r"^voluntarios/", include("preciosa.voluntarios.urls")),

)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.SITE_ID == 3:
    # las crawlers no son bienvenidos en el sitio de desarrollo
    from django.http import HttpResponse
    urlpatterns += patterns('',
                            (r'^robots\.txt$',
                             lambda r: HttpResponse("User-agent: *\nDisallow: /",
                                                    mimetype="text/plain"))
                            )

preciosa/voluntarios/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns("preciosa.voluntarios.views",
    url(r"^$", 'dashboard', name='voluntarios_dashboard'),      # noqa
    url(r"^mapa_categorias/$", 'mapa_categorias', name='mapa_categorias'),
    url(r"^logos/$", 'logos', name='logos'),
    url(r"^logos/marca/(?P<pk>\d+)/paso-(?P<paso>1|2)/$", 'logos', name='logos_marca'),
    url(r"^marca/$", 'alta_marca', name='alta_marca'),
    url(r"^marca/autocomplete/nombre/$", 'autocomplete_nombre_marca',
        name='autocomplete_nombre_marca'),
    url(r"^marca/voto/(?P<pk>\d+)/$", 'voto_item', name='voto_item'),
    url(r"^sucursal/$", 'alta_cadena_sucursal', name='alta_cadena_sucursal'),
    url(r"^sucursal/autocomplete/nombre/$", 'autocomplete_nombre_sucursal',
        name='autocomplete_nombre_sucursal'),
    url(r"^sucursal/voto/(?P<pk>\d+)/$", 'voto_item', name='voto_item'),
    url(r"^sucursal/geo_code/$", 'geo_code_data', name='geo_code_data')
)

preciosa/acuerdos/models.py
# -*- coding: utf-8 -*-
"""
esta app modela el programa Precios Cuidados
ver https://github.com/mgaitan/preciosa/issues/137
"""

from django.db import models
from django.db.models.signals import m2m_changed
from django.db.models import Q
from cities_light.models import City


class Region(models.Model):
    """una region incluye provincias y opcionalmente agrega o quita
    algunas ciudades. especificas"""

    nombre = models.CharField(max_length=150)
    provincias = models.ManyToManyField('cities_light.Region',
                                        related_name='incluida_en_region_acuerdo')
    ciudades_incluidas = models.ManyToManyField('cities_light.City',
                                                related_name='incluida_en_region_acuerdo')
    ciudades_excluidas = models.ManyToManyField('cities_light.City',
                                                related_name='excluida_de_region_acuerdo')

    # este campo es una denormalización para simplificar y agilizar queries
    # se actualiza llamando a _calcular_ciudades cuando algunos los otros m2m
    # cambia.
    ciudades = models.ManyToManyField('cities_light.City',
                                      related_name='region_en_acuerdo',
                                      editable=False)

    def __unicode__(self):
        return self.nombre

    def _calcular_ciudades(self):
        """devuelve un QS de ciudades incluyendo todas las ciudades
           que abarca la region. considera provincia, ciudades incluidas y
           excluidas"""
        base = City.objects.filter(Q(incluida_en_region_acuerdo=self) |
                                   Q(region__in=self.provincias.all()))
        return base.exclude(Q(excluida_de_region_acuerdo=self))


def actualizar_ciudades_de_region(sender, **kwargs):
    region = kwargs['instance']
    region.ciudades.clear()
    region.ciudades.add(*region._calcular_ciudades())

m2m_changed.connect(actualizar_ciudades_de_region,
                    sender=Region.ciudades_incluidas.through)
m2m_changed.connect(actualizar_ciudades_de_region,
                    sender=Region.ciudades_excluidas.through)
m2m_changed.connect(actualizar_ciudades_de_region,
                    sender=Region.provincias.through)


class Acuerdo(models.Model):
    nombre = models.CharField(max_length=150)
    region = models.ForeignKey(Region)
    sucursales = models.ManyToManyField('precios.Sucursal')
    cadenas = models.ManyToManyField('precios.Cadena')

    def __unicode__(self):
        tipo = 'Cadenas Nacionales' if self.cadenas.exists() else 'Super Regionales'
        return u"%s (%s) - %s" % (self.nombre, self.region, tipo)


class PrecioEnAcuerdoManager(models.Manager):

    def en_acuerdo(self, producto, sucursal):
        """dado un producto y sucursal, devuelve una lista de diccionarios
            con el precio y el nombre del acuerdo"""

        qs = super(PrecioEnAcuerdoManager, self).get_queryset()
        qs = qs.filter(producto=producto)

        # para evitar calcular todo. Si bien hacemos una query mas,
        # el porcentaje de productos bajo acuerdo es muy pequeño
        # la mayoria de las veces no existe.
        if not qs.exists():
            return []

        if sucursal.cadena:
            # grandes cadenas.
            qs = qs.filter(Q(acuerdo__cadenas=sucursal.cadena) |
                           Q(acuerdo__sucursales=sucursal))
        else:
            qs = qs.filter(acuerdo__sucursales=sucursal)

        qs = qs.filter(acuerdo__region__ciudades=sucursal.ciudad)
        return qs.values('acuerdo__nombre', 'precio')


class PrecioEnAcuerdo(models.Model):
    objects = PrecioEnAcuerdoManager()

    acuerdo = models.ForeignKey(Acuerdo, related_name='precios_en_acuerdo')
    producto = models.ForeignKey('precios.Producto')
    precio = models.DecimalField(max_digits=8, decimal_places=2)

preciosa/voluntarios/models.py
# -*- coding: utf-8 -*-
"""
en esta aplicacion iran modelos y vistas auxiliares para
realizar tareas de saneamiento de dato masivo basadas
en usuarios voluntarios

la mayoria de los modelos contendran informacion que es
meramente auxiliar y a futuro podra ser eliminada
"""


from django.db import models
from django.contrib.auth.models import User
from model_utils.models import TimeStampedModel

from preciosa.precios.models import (Cadena, Categoria, Marca,
                                    EmpresaFabricante, Sucursal)
from collections import Counter


class MapaCategoria(TimeStampedModel):
    """
    modelo auxiliar para resolver el ticket #64

    guardamos el aporte del usuario y cuando haya suficientes
    eligiremos la combinación origen->destino mas repetida
    """

    origen = models.ForeignKey(Categoria, related_name='mapeo_origen')
    # notar que todas las CAT de origen son depth=2 entonces
    # no hay peligro de colision
    destino = models.ForeignKey(Categoria,
                                related_name='mapeo_destino',
                                verbose_name=u"Yo la asociaría con...",
                                limit_choices_to={'depth': 3})
    user = models.ForeignKey(User, editable=False)
    separar = models.BooleanField(verbose_name=u'Esta lista debería separarse en '
                                               u'varias categorías', default=False)
    comentario = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return u'%s ---> %s' % (self.origen, self.destino)

    class Meta:
        # solo una eleccion por usuario por categoria
        unique_together = ('user', 'origen')

    @classmethod
    def resultados(cls):
        mapa = []
        for origen in Categoria.por_clasificar():
            counter = Counter([voto.destino for voto in
                               cls.objects.filter(origen=origen)])
            mejor_destino = counter.most_common(1)
            mapa.append((origen, mejor_destino))
        return mapa

    @classmethod
    def categorizables_por_voluntario(cls, user):
        ya_hechas = MapaCategoria.objects.filter(user=user).values_list(
            'origen_id', flat=True)
        return Categoria.por_clasificar().exclude(id__in=ya_hechas)


class EntidadCreadaVoluntario(TimeStampedModel):
    user = models.ForeignKey(User, editable=False)

    class Meta:
        abstract = True


class VotoVoluntario(TimeStampedModel):
    user = models.ForeignKey(User, editable=False)
    voto = models.IntegerField()

    class Meta:
        abstract = True


class MarcaEmpresaCreada(EntidadCreadaVoluntario):
    """un modelo para trackear la creacion de marcas
    o empresas por voluntarios"""
    marca = models.ForeignKey(Marca, editable=False, null=True)
    empresa = models.ForeignKey(EmpresaFabricante, editable=False, null=True)


class VotoMarcaEmpresaCreada(VotoVoluntario):
    u"""un usuario vota el item que creó otro """
    item = models.ForeignKey(MarcaEmpresaCreada, related_name='votos')


class SucursalCadenaCreada(EntidadCreadaVoluntario):
    u"""un modelo para trackear la creación de sucursales o cadenas
    de supermercados por voluntarios.

    """
    sucursal = models.ForeignKey(Sucursal, editable=False, null=True)
    cadena = models.ForeignKey(Cadena, editable=False, null=True)


class VotoSucursalCadenaCreada(VotoVoluntario):
    u"""un usuario vota el item que creó otro """
    item = models.ForeignKey(SucursalCadenaCreada, related_name='votos')

preciosa/accounts/forms.py
from django import forms


import account.forms


class SignupForm(account.forms.SignupForm):
    subscribe_to_newsletter = forms.BooleanField(
    	label="Suscribirse al boletin",
        required=False
    )

preciosa/voluntarios/forms.py
# -*- coding: utf-8 -*-
import autocomplete_light
import floppyforms as forms

from cities_light.models import City
from preciosa.precios.models import (Categoria, Cadena, EmpresaFabricante,
                                     Marca, Sucursal)
from preciosa.voluntarios.models import MapaCategoria
from preciosa.voluntarios.mixins import CleanNombreMixin


class PointWidget(forms.gis.PointWidget, forms.gis.BaseGMapWidget):
    map_width = 500
    map_height = 350


class MapaCategoriaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(MapaCategoriaForm, self).__init__(*args, **kwargs)
        self.fields['origen'].queryset = Categoria.por_clasificar()
        self.fields[
            'comentario'].help_text = u'Por favor, indicá las categorías que usarías'

    class Meta:
        model = MapaCategoria
        widgets = {
            'origen': forms.HiddenInput(),
        }


class MarcaModelForm(forms.ModelForm, CleanNombreMixin):

    # flag para que el mixin distinga que modelform es
    model_related = Marca

    qs = EmpresaFabricante.objects.all().order_by('nombre')
    # en el form lo hacemos obligatorio
    fabricante = forms.ModelChoiceField(queryset=qs,
                                        help_text='Por favor, revisá bien este campo.')

    class Meta:
        model = Marca
        exclude = ['logo', 'logo_cropped']
        help_texts = {
            'nombre': 'Tiene que ser una marca nueva. '
                      'Si la que querés agregar aparece en la lista, '
                      'quiere decir que ya la conocemos.',
        }


class LogoMarcaModelForm(forms.ModelForm):

    """form para subir/editar el logo de una marca"""
    class Meta:
        model = Marca
        fields = ['logo', 'logo_cropped']


class EmpresaFabricanteModelForm(forms.ModelForm, CleanNombreMixin):
    model_related = EmpresaFabricante

    class Meta:
        model = EmpresaFabricante
        fields = ['nombre']
        help_texts = {
            'nombre': 'Tiene que ser una empresa nueva.'
        }


class CadenaModelForm(forms.ModelForm, CleanNombreMixin):
    model_related = Cadena
    cadena_madre = forms.ModelChoiceField(Cadena.objects.all(),
                                          label=u'Pertenece a', required=False,
                                          help_text=u'Por ejemplo, Jumbo y Vea son de Cencosud')   # noqa

    class Meta:
        model = Cadena
        fields = ['cadena_madre', 'nombre']


class SucursalModelForm(forms.ModelForm, CleanNombreMixin):
    model_related = Sucursal
    max_cantidad_palabras = 4
    max_largo = 30
    puede_ser_vacio = True

    ciudad = forms.ModelChoiceField(
        City.objects.all(), widget=autocomplete_light.ChoiceWidget('CityAutocomplete'))

    ubicacion = forms.gis.PointField(widget=PointWidget, required=False)

    class Meta:
        model = Sucursal
        fields = ('cadena', 'nombre', 'ciudad', 'direccion', 'ubicacion', 'cp',
                  'telefono', 'horarios')

preciosa/accounts/views.py
from .forms import SignupForm

from newsletter.models import Subscription, Newsletter

import account.views


class SignupView(account.views.SignupView):
    form_class = SignupForm

    def after_signup(self, form):

        if form.cleaned_data["subscribe_to_newsletter"]:

            if not Subscription.objects.filter(
                email_field=form.cleaned_data['email']
            ).exists():
                Subscription.objects.create(
                    user=self.created_user,
                    newsletter=Newsletter.objects.first(),
                    subscribed=True
                )

        super(SignupView, self).after_signup(form)

preciosa/acuerdos/views.py
from django.shortcuts import render

# Create your views here.

preciosa/datos/views.py
from django.shortcuts import render

# Create your views here.

preciosa/flatpagex/views.py
from django.shortcuts import render

# Create your views here.

preciosa/templates/voluntarios/alta_cadena_sucursal.html
{% extends "voluntarios/base.html" %}
{% load bootstrap %}
{% load humanize %}
{% load cropping thumbnail %}

{# pongo los mensajes más cerca del formulario #}
{% block messages %}{% endblock  %}
{% block body %}
    <h1 class="page-header">Agregar sucursal</h1>
     <p class="lead">
        Necesitamos conocer todas las sucursales del país, así podremos
        recibir y enviar precios más precisos.
        Además, nos servirá para hacer estadísticas. Por ejemplo <strong> ¿Cuál cadena de super aumentó más los precios en tu ciudad?</strong>.
    </p>
    <p class="lead">
        Tratá de poner la dirección con precisión y luego, si hacer falta, corregí la ubicación en el mapita.
    </p>
    {% include "_messages.html" %}

<div class="row">
    <div class="col-lg-5">
        {{ form_sucursal.media }}
        <h3>Agregar una nueva sucursal</h3>
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_sucursal|bootstrap }}
            <input class="btn btn-primary btn-lg" type="submit" name="btn_form_sucursal" value="Agregar esta sucursal" />
        </form>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-info">
            <div class="panel-heading">¿No está la cadena de supermercados que buscás?</div>
            <div class="panel-body">
                 <form method="post" action="." enctype="multipart/form-data" >
                     {% csrf_token %}
                     {{ form_cadena|bootstrap }}
                     <input class="btn btn-primary col-lg-12" type="submit" name="btn_form_cadena" value="Agregar" />
                 </form>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="chat-panel panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-comments fa-fw"></i>Votar actividad recientemente
            </div>
            <div class="panel-body">
                <ul class="chat">
                    {% for item in creados %}
                    <li class="left clearfix">
                    <span class="chat-img pull-left">
                        <p>
                        <button title="Parece correcto" class="btn btn-success btn-circle vot_yes" data-pk="{{ item.id }}" type="button">
                            <i class="fa fa-check"></i>
                        </button>
                        </p>
                        <p>
                        <button title="Parece incorrecto" class="btn btn-danger btn-circle vot_no" data-pk="{{ item.id }}" type="button">
                            <i class="fa fa-times"></i>
                        </button>
                        </p>
                    </span>
                    <div class="chat-body clearfix">
                        <div class="header">
                            <strong class="primary-font">{{ item.user.username }} </strong>
                            <small class="pull-right text-muted">
                                <i class="fa fa-clock-o fa-fw"></i> {{ item.created|naturaltime }}
                            </small>
                        </div>
                        <p>
                        {% if item.sucursal %}
                            creó la sucursal <strong>{{ item.sucursal.nombre }}</strong>
                            perteneciente a <strong>{{ item.sucursal.cadena.nombre }}</strong>
                        {% else %}
                            creó la cadena de supermercados
                            <strong>{{ item.cadena.nombre }}</strong>
                        {% endif %}
                        </p>
                    </div>
                    </li>
                    {% endfor %}
                </ul>
           </div><!-- /.panel-body -->
        </div>
    </div>
</div>

{% endblock body %}
{% block extra_footer %}
    <script type="text/javascript">

    $(function(){
        $(document).ready(function(){
            // Make a javascript Autocomplete object and set it up
            var autocomplete2 = $('#id_nombre').yourlabsAutocomplete({
                url: '{% url "autocomplete_nombre_sucursal" %}',
            });

            $('button.vot_yes').on('click', function(){
                var $but = $(this);
                var pk = $but.data('pk');
                $.post('./voto/' + pk + '/',
                       {'voto': true, 'model': 'voluntarios.SucursalCadenaCreada'},
                       function(response){
                           if (response.result){
                               $but.parents('.left').fadeOut();
                           }
                       }
                );
            });

            $('button.vot_no').on('click', function(){
                var $but = $(this);
                var pk = $but.data('pk');
                $.post('./voto/' + pk + '/', {'voto': false, 'model':
                  'voluntarios.SucursalCadenaCreada'}, function(response){
                    if (response.result){
                        $but.parents('.left').fadeOut();
                    }
                });
            });

            $('input[name="direccion"], #id_ciudad').on('change', function(data){
                var url = './geo_code/?ciudad=' + $('#id_ciudad').val() +  '&direccion=' + $('#id_direccion').val();

                var epsg4326 = new OpenLayers.Projection("EPSG:4326");
                var epsg900913 = new OpenLayers.Projection("EPSG:900913");

                var layer = map_ubicacion.map.layers[1];
                // http://jsfiddle.net/_DR_/SMnUJ/
                drag = new OpenLayers.Control.DragFeature(layer, {
                       autoActivate: true,
                });
                map_ubicacion.map.addControl(drag);

                $.get(url, function(data){
                    if (data){

                    var center = new OpenLayers.LonLat(data.lon, data.lat).transform(epsg4326, epsg900913);
                    var point = new OpenLayers.Geometry.Point(center.lon,center.lat);
                    layer.addFeatures([new OpenLayers.Feature.Vector(point)]);
                    if (data.direccion){
                        var zoom = 16;
                    }else{
                        var zoom = 15;
                    }
                    map_ubicacion.map.setCenter(center, 15);
                    }
                });
            });
        });
    });
    </script>
{% endblock extra_footer %}

preciosa/templates/voluntarios/autocomplete_nombre_marca.html
{% load url from future %}

{% for marca in marcas %}
    <a class="div choice" href="#">{{ marca.nombre  }}  {% if marca.fabricante %}
        ({{ marca.fabricante.nombre }})
    {% endif %}</a>
{% endfor %}

preciosa/templates/voluntarios/autocomplete_nombre_sucursal.html
{% load url from future %}

{% for sucursal in sucursales %}
<div class="choice">
    {{ sucursal.nombre  }}  
    {% if sucursal.cadena %}
        ({{ sucursal.cadena.nombre }})
    {% endif %}
</div>
{% endfor %}

preciosa/templates/voluntarios/base.html
{% extends "base.html" %}
{% load staticfiles %}




{% block extra_head %}
    <link rel="stylesheet" href="{% static 'feedback/main.css' %}"/>
{% endblock extra_head %}

{% block body_top %}<a class="btn btn-min pull-right" style="margin-bottom:-40px" href="{% url "voluntarios_dashboard" %}"><i class="fa fa-chevron-left"></i> Volver al panel de voluntarios</a> {% endblock body_top %}

{% block extra_footer %}
    <script src="{% static 'feedback/jquery.form.js' %}"></script>
    <script src="{% static 'feedback/main.js' %}"></script>
    {% include "feedback/button.html" %}
{% endblock extra_footer %}

preciosa/templates/voluntarios/mapa_categorias.html
{% extends "voluntarios/base.html" %}
{% load bootstrap %}

{# pongo los mensajes más cerca del formulario #}
{% block messages %}{% endblock  %}
{% block body %}


        <h1 class="page-header">Asociar categorías</h1>


    <p class="lead">Desde esta sección podés ayudar a asociar algunas listas de productos que no estamos seguros en qué categoría poner. Leé las "pistas" que conocemos y elegí la categoría de destino que más te parezca. Cuando haya sufientes coincidencias, moveremos los artículos no clasificados a esa categoría.
     </p>

    <p class="lead">Tomáte tu tiempo, somos muchos y muchas ayudando, y más vale calidad que cantidad.</p>

        {% include "_messages.html" %}



<div class="row">
    <div class="col-lg-3 pull-right">
        {% include "_progress.html" %}
    </div>
    </div>

    <dl>
        <dt>Origen</dt>
        <dd>La lista de origen tiene que ver con <strong>"{{ origen.nombre}}"</strong></dd>
        <dt>Contiene</dt>
        <dd>Algunos de los productos que contiene son:

            <ul>
                {% for producto in productos_ejemplo %}
                    <li>{{ producto.descripcion }}</li>
                {% endfor %}
            </ul>

            </dd>
    </>


    <form action="" method="post">{% csrf_token %}
        {{ form|bootstrap }}
        <input class="btn btn-primary btn-lg" type="submit" value="Me parece que es la mejor opción" />


        <a class="btn btn-default" href="{% url 'mapa_categorias' %}">No tengo idea, paso</a>

    </form>
{% endblock body %}


{% block extra_footer %}
    {{ block.super }}

    <script type="text/javascript">
        var $comment =  $('#id_comentario').parents('.form-group');
        $comment.hide();
        $('#id_separar').on('change', function(){ $comment.toggle() });

    </script>
{% endblock extra_footer %}